# Dockerfile.frontend
# Use a Node.js image
FROM node:22

# Set the working directory in the container
WORKDIR /cinstar/ cinstar_frontend_demo

# Copy the React app code into the container
COPY ./cinstar_frontend_demo/ .

# Install dependencies
RUN npm install

# Build the React app
RUN npm run build

# Expose port for the ReactJS application
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
